apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeseal-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/obynodavid12/argocd-demo.git
    targetRevision: HEAD
    path: argocd/kubeseal-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeseal-app
  syncPolicy: 
    automated:
      prune: false
      selfHeal: false