apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/obynodavid12/devops.git
    targetRevision: HEAD
    path: argocd/lab-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-app
  syncPolicy: 
    automated:
      prune: false
      selfHeal: false

      