apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy: 
    automated:
      prune: false
      selfHeal: false  
  sources:
    - repoURL: https://github.com/obynodavid12/devops.git
      path: argocd/lab-app
      targetRevision: HEAD
      # targetRevision: 8.5.1

    - repoURL: https://github.com/obynodavid12/argocd-demo.git
      path: argocd/lab-app
      targetRevision: HEAD
      