apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-mysql-pv-claim
  namespace: dev3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
