apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: dev3
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/vol1     # make sure this path is created on node kubenode02 "mkdir -p /mnt/disks/vol1"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-worker2
